name = "fight-castle"
main = "src/index.js"
compatibility_date = "2026-08-01"

[durable_objects]
bindings = [
  { name = "FIGHT_ROOMS", class_name = "FightRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FightRoom"]
